apiVersion: v1
kind: ConfigMap
metadata:
  name: gratitude-config
  namespace: gratitude-app
data:
  # Database connection variables
  PGUSER: "grat-pg"
  PGDATABASE: "gratitude"
  PGPORT: "5432"
  PGHOST: "grat-postgres-service"
  # Service ports
  API_GATEWAY_PORT: "50050"
  ENTRIES_SERVICE_PORT: "50051"
  MOODS_API_PORT: "50052"
  STATS_API_PORT: "50053"
  STATS_SERVICE_PORT: "50054"
  MOODS_SERVICE_PORT: "50055"
  SERVER_MAIN_PORT: "50056"
