apiVersion: v1
kind: Service
metadata:
  name: grat-api-gateway-service
  namespace: gratitude-app
  labels:
    app: grat-api-gateway
spec:
  ports:
  - port: 50050
    targetPort: 50050
    protocol: TCP
  selector:
    app: grat-api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: grat-entries-service-service
  namespace: gratitude-app
  labels:
    app: grat-entries-service
spec:
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
  selector:
    app: grat-entries-service
---
apiVersion: v1
kind: Service
metadata:
  name: grat-moods-api-service
  namespace: gratitude-app
  labels:
    app: grat-moods-api
spec:
  ports:
  - port: 50052
    targetPort: 50052
    protocol: TCP
  selector:
    app: grat-moods-api
---
apiVersion: v1
kind: Service
metadata:
  name: grat-stats-api-service
  namespace: gratitude-app
  labels:
    app: grat-stats-api
spec:
  ports:
  - port: 50053
    targetPort: 50053
    protocol: TCP
  selector:
    app: grat-stats-api
---
apiVersion: v1
kind: Service
metadata:
  name: grat-stats-service-service
  namespace: gratitude-app
  labels:
    app: grat-stats-service
spec:
  ports:
  - port: 50054
    targetPort: 50054
    protocol: TCP
  selector:
    app: grat-stats-service
---
apiVersion: v1
kind: Service
metadata:
  name: grat-moods-service-service
  namespace: gratitude-app
  labels:
    app: grat-moods-service
spec:
  ports:
  - port: 50055
    targetPort: 50055
    protocol: TCP
  selector:
    app: grat-moods-service
---
apiVersion: v1
kind: Service
metadata:
  name: grat-server-main-service
  namespace: gratitude-app
  labels:
    app: grat-server-main
spec:
  ports:
  - port: 50056
    targetPort: 50056
    protocol: TCP
  selector:
    app: grat-server-main
---
apiVersion: v1
kind: Service
metadata:
  name: grat-frontend-service
  namespace: gratitude-app
  labels:
    app: grat-frontend
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: grat-frontend
